/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "trapmodule.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_alarmInfo1_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid alarmInfo1_oid[] = { 1,3,6,1,4,1,1005,2,1,1,1 };
    const oid alarmContent_oid[] = { 1,3,6,1,4,1,1005,2,1,2,1, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        alarmInfo1_oid, sizeof(alarmInfo1_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        alarmContent_oid, OID_LENGTH(alarmContent_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for alarmContent */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_alarmInfo2_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid alarmInfo2_oid[] = { 1,3,6,1,4,1,1005,2,1,1,2 };
    const oid alarmContent_oid[] = { 1,3,6,1,4,1,1005,2,1,2,1, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        alarmInfo2_oid, sizeof(alarmInfo2_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        alarmContent_oid, OID_LENGTH(alarmContent_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for alarmContent */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
