/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TRAPMODULE_H
#define TRAPMODULE_H

/* function declarations */
int send_alarmInfo1_trap(void);
int send_alarmInfo2_trap(void);

#endif /* TRAPMODULE_H */
