/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TESTDATA_H
#define TESTDATA_H

/* function declarations */
void init_testData(void);
Netsnmp_Node_Handler handle_getData1;
Netsnmp_Node_Handler handle_getddata1;
Netsnmp_Node_Handler handle_getddata2;

#endif /* TESTDATA_H */
